---
name: Release Module

on:
  workflow_call:
    inputs:
      tag:
        required: true
        type: string
      prerelease:
        type: choice
        description: "Pre-Release?"
        required: true
        options:
          - true
          - false
        default: true
      directory:
        required: true
        type: string

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v4

      - name: Build
        run: |
          go build -v ./...

      - name: Tag
        run: |
          if ! [[ ${{ github.event.inputs.tag }} =~ ^v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo "Tag needs to be vX.Y.Z, e.g. v1.2.3"
            exit 1
          fi
          git tag ${{ github.event.inputs.tag }}
          git push origin ${{ github.event.inputs.tag }}

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          prerelease: ${{ github.event.inputs.prerelease }}
          name: ${{ github.event.inputs.tag }}
          tag_name: ${{ github.event.inputs.tag }}
          fail_on_unmatched_files: true
          generate_release_notes: true