---
name: Release

on:
  workflow_call:
    inputs:
      tag:
        required: true
        type: string
      prerelease:
        required: true
        type: boolean
      files:
        required: true
        type: string
      submodule_tag:
        required: false
        type: string

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Submodule Tag
        if: ${{ github.event.inputs.submodule_tag }}
        run: |
          if ! [[ ${{ github.event.inputs.submodule_tag }} =~ ^[a-zA-Z0-9\_\-]+\/v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo "Tag needs to be folder/vX.Y.Z, e.g. client/v1.2.3"
            exit 1
          fi
          git tag ${{ github.event.inputs.submodule_tag }}
          git push origin ${{ github.event.inputs.submodule_tag }}

      - name: Tag
        run: |
          if ! [[ ${{ github.event.inputs.tag }} =~ ^v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo "Tag needs to be vX.Y.Z, e.g. v1.2.3"
            exit 1
          fi
          git tag ${{ github.event.inputs.tag }}
          git push origin ${{ github.event.inputs.tag }}

      - name: Setup Go
        uses: actions/setup-go@v5

      - name: Build
        run: |
          go build -v ./cmd/...

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          prerelease: ${{ github.event.inputs.prerelease }}
          files: ${{ github.event.inputs.files }}
          name: ${{ github.event.inputs.tag }}
          tag_name: ${{ github.event.inputs.tag }}
          fail_on_unmatched_files: true
          generate_release_notes: true
